# Generated by Django 2.0 on 2018-10-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial_groups'),
        ('api', '0003_initial_languages'),
    ]

    operations = [
    ]
