# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merged_initial_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.FileField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_types/'),
        ),
    ]
