# Generated by Django 2.0 on 2018-01-01 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userauthcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcredentials',
            name='jti',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_credentials', related_query_name='auth_credential', to='api.User'),
        ),
    ]
