# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.FileField(null=True, upload_to='store/static/images/products/main/'),
        ),
    ]
