# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 07:47
from __future__ import unicode_literals

from django.db import migrations


def create_groups(apps, schema_editor):
  Group = apps.get_model('store', 'Group')
  Group.objects.get_or_create(name='reader')
  Group.objects.get_or_create(name='manager')
  Group.objects.get_or_create(name='admin')


class Migration(migrations.Migration):
  dependencies = [
    ('store', '0001_initial'),
  ]

  operations = [
    migrations.RunPython(create_groups)
  ]
