version: "3"
services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env.${ENV}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: ./backend
    env_file:
      - .env.${ENV}
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
