version: "3"
services:
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  backend:
    build: 
      context: ./backend
    environment:
      - SECRET_KEY=secret
      - DB_URL=db_url
      - ADMIN_EMAIL=email@email.com
      - ADMIN_PASSWORD=password
      - ELASTICSEARCH_URL=es:9200
      - ALLOWED_ORIGINS=http://www.test.com,http://test.com
      - AWS_ACCESS_KEY_ID=aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=aws_secret_key
      - AWS_BUCKET_NAME=aws_bucket_name
      - AWS_DEFAULT_REGION=eu-central-1
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
      - es
    links:
      - db
      - es
  web:
    build:
      context: ./web
    ports:
      - 80:80
    depends_on:
      - backend
    links:
      - backend
    volumes: 
      - ./nginx/conf.d:/etc/nginx/conf.d