version: "3"
services:
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build: git@github.com:teimurjan/eye8-backend.git
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - SECRET_KEY=secret_key
      - DB_URL=postgresql://db_user:db_password@db:5432/db_name
      - ADMIN_EMAIL=admin@example.com,admin2@example.com,
      - ADMIN_PASSWORD=admin_password1,admin_password2
      - ALLOWED_ORIGINS=http://www.allowed.origin,http://allowed.origin
      - AWS_ACCESS_KEY_ID=aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=aws_secret_access_key
      - AWS_BUCKET_NAME=aws_bucket_name
      - AWS_DEFAULT_REGION=aws_default_region
      - EMAIL_SMTP_SERVER=smtp.gmail.com
      - EMAIL_SMTP_PORT=465
      - EMAIL_USERNAME=broadcast@email.com
      - EMAIL_ORDERS_USERNAME=staff@email.com
      - EMAIL_PASSWORD=email_password
      - EMAIL_UNSUBSCRIBE_USERNAME=unsubscribe@email.com
      - HOST=https://host.com
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
  nginx:
    image: nginx:alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    links:
      - web
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  web:
    build: git@github.com:teimurjan/eye8-web.git
    args: 
      - SENTRY_DSN=sentry_dsn
    ports:
      - 3000:3000
    depends_on:
      - backend
