version: "3"
services:
  db:
    restart: always
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
