OK_CODE = 200
BAD_REQUEST_CODE = 400
FORBIDDEN_CODE = 403
UNAUTHORIZED_CODE = 401
SERVER_ERROR_CODE = 500
NOT_FOUND_CODE = 404

AUTHORIZATION_HEADER = 'HTTP_AUTHORIZATION'
ACCEPT_LANGUAGE_HEADER = 'HTTP_ACCEPT_LANGUAGE'
HTTP_X_APP_HEADER = 'HTTP_X_APP'
