# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(db_table='api_feature_type_x_category', related_name='feature_types', related_query_name='feature_type', to='api.Category')),
            ],
            options={
                'db_table': 'api_feature_type',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeatureType')),
            ],
            options={
                'db_table': 'api_feature_value',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'api_user_group',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('groups', models.ManyToManyField(db_table='api_user_permission_x_group', related_name='permissions', related_query_name=' permission', to='api.Group')),
            ],
            options={
                'db_table': 'api_user_permission',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(max_length=100, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='store/static/images/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Product')),
            ],
            options={
                'db_table': 'api_product_image',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('short_description', models.CharField(blank=True, max_length=100)),
                ('image', models.FileField(upload_to='store/static/images/products/main/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', related_query_name='product_type', to='api.Category')),
            ],
            options={
                'db_table': 'api_product_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProductType'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='product_types',
            field=models.ManyToManyField(db_table='api_feature_value_x_product_type', related_name='feature_values', related_query_name='feature_value', to='api.ProductType'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='products',
            field=models.ManyToManyField(db_table='api_feature_value_x_product', related_name='feature_values', related_query_name='feature_value', to='api.Product'),
        ),
    ]
