# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170717_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
