# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial_languages'),
        ('api', '0002_initial_groups'),
    ]

    operations = [
    ]
