# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170723_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
