ID_FIELD = 'id'
NAME_FIELD = 'name'
EMAIL_FIELD = 'email'
PASSWORD_FIELD = 'password'
PRICE_FIELD = 'price'
IMAGE_FIELD = 'image'
CATEGORY_FIELD = 'category'
CATEGORIES_FIELD = 'categories'
DESCRIPTION_FIELD = 'description'
SHORT_DESCRIPTION_FIELD = 'short_description'
QUANTITY_FIELD = 'quantity'
DISCOUNT_FIELD = 'discount'
GROUP_FIELD = 'group'
FEATURE_TYPES_FIELD = 'feature_types'
AUTH_FIELDS = 'auth'

TOKEN_KEY = 'token'
DATA_KEY = 'data'
