MESSAGE_KEY = 'message'
MESSAGE_OK = {MESSAGE_KEY: 'ok'}

# JSON KEYS
TOKEN_JSON_KEY = 'token'
GROUP_JSON_KEY = 'group'
NAME_JSON_KEY = 'name'
ID_JSON_KEY = 'id'
DATA_JSON_KEY = 'data'

# STATUS CODES
OK_CODE = 200
BAD_REQUEST_CODE = 400
FORBIDDEN_CODE = 403
NOT_FOUND_CODE = 404
